server:
  host: 0.0.0.0
  port: 9091
log:
  level: info
jwt_secret: lMZDpAfxYUaAMeJ4TsMvCgqySmtIEUZdHohGYTovjp3LJYVVVCEZxmpkGPA1Igfh
default_redirection_url: https://app.example.com
 
authentication_backend:
  file:
    path: /config/users_database.yml
 
access_control:
  default_policy: deny
  rules:
    - domain:
        - "auth.example.com"
      policy: bypass
    - domain:
        - "example.com"
        - "*.example.com"
        - "app.example.com"
      policy: one_factor
 
session:
  name: authelia_session
  secret: JzHeqkBcUar40jaFSpGrKvip3DtqjUea2EDxOAtkYhn0tSfVW8Wf2WLI3AQk7bSf
  expiration: 12h           # 12 hours
  inactivity: 45m           # 45 minutes
  remember_me_duration: 1M  # 1 month
  domain: example.com
 
  redis:
    #host: redis_authelia
    host: 172.20.0.50
    port: 6379
 
regulation:
  max_retries: 3
  find_time: 5m
  ban_time: 15m
 
storage:
  encryption_key: 6JoZlbtlXpSkZChwKMvYTcbMIQM2W0XvmYLkgJzGfVbWpvdLDSt3Q7WYxlBZaMrQ
  local:
    path: /config/db.sqlite3
 
notifier:
  filesystem:
    filename: /config/notification.txt
