# Use the official LinuxServer WireGuard image as base
FROM lscr.io/linuxserver/wireguard:latest

# Set environment variables
ENV PUID=1000 \
    PGID=1000 \
    TZ=Etc/UTC \
    PEERS=1 \
    LOG_CONFS=true

#ENTRYPOINT ["/usr/local/bin/start-wireguard.sh"]
